manifest/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <label>Mail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifest/force-app/main/default/objects/Mail__c/fields/Delivered__c.field-meta.xml
<CustomField>
    <fullName>Delivered__c</fullName>
    <label>Delivered</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>yes</fullName>
            </value>
            <value>
                <fullName>no</fullName>
                <default>true</default>
                <label>no</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

manifest/force-app/main/default/objects/Mail__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Insurance?</label>
    <type>Checkbox</type>
</CustomField>

manifest/force-app/main/default/objects/Mail__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <description>Tracks shipments</description>
    <displayFormat>PO# {00000000}</displayFormat>
    <externalId>true</externalId>
    <label>Tracking Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/TrackingController.cls
public class TrackingController {

    public List<Mail__c>mailList{get;set;}
    public String trackingID {get;set;}
    
    
    public TrackingController(){
  		mailList = new List<Mail__c>();
		trackingID = '';
    }
    
    public void ConfirmButtonPressed(){
        mailList = [SELECT Tracking_Number__c, Name, Address__c, Delivered__c, Insurance__c FROM Mail__c WHERE Tracking_Number__c = :trackingID];
        system.debug('button pressed');
    system.debug(TrackingID);
    system.debug(mailList);}
    
}